-- Match settings: kickoff time, duration, and venue, editable from /admin.
-- These replace what used to be hardcoded values in Hero.jsx, useCountdown.js,
-- MapSection.jsx, and the App.jsx footer.

-- Ensure config has a stable primary key to update against, regardless of
-- how the table was originally created (Supabase's table editor normally
-- adds one automatically, but this is defensive in case it doesn't exist).
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_name = 'config' and column_name = 'id'
  ) then
    alter table config add column id bigint generated by default as identity primary key;
  end if;
end $$;

alter table config add column if not exists kickoff_at        timestamptz;
alter table config add column if not exists duration_minutes  integer not null default 90;
alter table config add column if not exists location_name     text;
alter table config add column if not exists location_address  text;
alter table config add column if not exists map_embed_url     text;
alter table config add column if not exists directions_url    text;

-- Backfill the existing single row with the values that used to be hardcoded.
-- Adjust kickoff_at below if your match date/time has since changed.
update config set
  kickoff_at        = coalesce(kickoff_at, '2026-06-25 21:00:00+03'::timestamptz),
  duration_minutes  = coalesce(duration_minutes, 90),
  location_name     = coalesce(location_name, 'Al-Rawad Fields — Riyadh'),
  location_address  = coalesce(location_address, 'Riyadh, Saudi Arabia'),
  map_embed_url     = coalesce(map_embed_url, 'https://maps.google.com/maps?q=24.78415,46.7259482&z=17&output=embed'),
  directions_url    = coalesce(directions_url, 'https://maps.app.goo.gl/ox34GqnsVmi3ownX6');

-- Allow the admin dashboard (which uses the same public anon key as the
-- rest of the app — see the security note from the admin-login PR) to
-- write match settings.
drop policy if exists "Public update config" on config;
create policy "Public update config" on config for update using (true) with check (true);
